public enum CompensationType {
    TIMEANDAHALF, DOUBLE, TRIPLE, OVERTIME, THREESIXTEENTHS, TWOEIGHTHS, ONESIXTH, REFRESHMENTS, ONEEIGHTH, ONEHUNDRED, HOTANDCOLDPLUSVEGETARIANMEAL, TWOSIXTHSOROVERTIMEGREATER
}
